from sqlalchemy import Column, Integer, String, Text, DateTime
from sqlalchemy.ext.declarative import declarative_base
from datetime import datetime

Base = declarative_base()

class Paper(Base):
    __tablename__ = "papers"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, index=True)
    author = Column(String)
    year = Column(String)
    abstract = Column(Text)
    department = Column(String, default="N/A")
    keywords = Column(Text, default="")
    project_type = Column(String, default="N/A")
    degree_program = Column(String, default="N/A")
    citation_count = Column(Integer, default=0)
    view_count = Column(Integer, default=0)
    file_path = Column(String)

    # ── Full extracted text (shown in "Regular" / full-text view) ─────────────
    introduction = Column(Text, nullable=True)
    methods = Column(Text, nullable=True)
    results = Column(Text, nullable=True)
    discussion = Column(Text, nullable=True)

    # ── AI-generated summaries (shown in 2-column IMRAD view) ─────────────────
    # Generated by imrad_summary_service.summarise_all() after upload.
    # Null means not yet generated (fall back to full text in the UI).
    introduction_summary = Column(Text, nullable=True)
    methods_summary = Column(Text, nullable=True)
    results_summary = Column(Text, nullable=True)
    discussion_summary = Column(Text, nullable=True)

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def sections_dict(self) -> dict:
        """Return full-text sections as a dict for imrad_summary_service."""
        return {
            "introduction": self.introduction or "",
            "methods":      self.methods or "",
            "results":      self.results or "",
            "discussion":   self.discussion or "",
        }

    def summaries_dict(self) -> dict:
        """Return cached summaries as a dict."""
        return {
            "introduction": self.introduction_summary,
            "methods":      self.methods_summary,
            "results":      self.results_summary,
            "discussion":   self.discussion_summary,
        }